#!/bin/bash -x

# get the date
date=$(date)

#get the topic
topic=$1

#filename to write
filename="${HOME}/${topic}notes.txt"

#Ask user for input
read -p "Your note: =" note

echo $(date): $note >> "$filename"
echo "Note '$note' saved to $filename"
